# Generated by Django 4.1.7 on 2023-09-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_unlisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
    ]
