# Generated by Django 4.1.7 on 2023-03-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='addProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
            ],
        ),
    ]
