# Generated by Django 4.1.7 on 2023-03-28 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_addproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
